- hosts: s.camin.us
  user: centos
  sudo: True
  tasks:
    - name: install epel
      action: yum pkg=http://lug.mtu.edu/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=installed
    - name: install ypserv
      action: yum pkg=ypserv state=latest
    - name: configure ypserv
      action: copy src=../config/ypserv.conf dest=/etc/ypserv.conf
      notify:
      - restart ypserv
    - name: enable ypserv
      action: service name=ypserv state=running
    - name: update NIS database
      action: command chdir=/var/yp make
    - name: install packages
      action: yum pkg={{item}} state=installed
      with_items:
        - nfs-utils
        - java-1.7.0-openjdk
        - s3cmd
    - name: start nfs server
      action: service name=nfs state=started
    - name: configure nfs exports
      action: copy src=../config/nfs-exports dest=/etc/exports
    - name: install beanstalkd
      action: yum pkg={{item}} state=installed
      with_items:
        - https://kojipkgs.fedoraproject.org//packages/daemonize/1.7.3/7.el7/x86_64/daemonize-1.7.3-7.el7.x86_64.rpm 
        - https://kojipkgs.fedoraproject.org//packages/beanstalkd/1.9/2.el6/x86_64/beanstalkd-1.9-2.el6.x86_64.rpm
    - name: start beanstalkd
      action: service name=beanstalkd state=started
  handlers:
    - name: restart ypserv
      action: service name=ypserv state=restarted

