---
- hosts: localhost
  user: ec2-user
  connection: local
  vars:
    - caminus_root: /srv/caminus
  vars_files:
    - ../private/django_local_settings.yml
  tasks:
    - name: Install epel
      action: yum pkg=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=installed
    - name: install {{item}}
      action: yum pkg={{item}} state=latest
      with_items:
        - python-pip
        - MySQL-python
        - git
        - gcc
        - python-devel
    - name: pip install uwsgi
      action: pip name=uwsgi state=latest
    - name: create uwsgi user
      action: user name=uwsgi system=yes
    - name: configure uwsgi
      action: template src=../config/uwsgi.conf dest=/etc/uwsgi.ini
    - name: checkout caminus
      action: git accept_hostkey=true repo=git://github.com/caminus/caminus.git dest={{caminus_root}}/app/ version=HEAD
    - name: configure caminus
      action: template src=../config/local_settings.py dest={{caminus_root}}/app/caminus/local_settings.py
