ITEMS = [
  {
    'name': 'AIR',
    'id': 0,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STONE',
    'id': 1,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GRASS',
    'id': 2,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIRT',
    'id': 3,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COBBLESTONE',
    'id': 4,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD',
    'id': 5,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SAPLING',
    'id': 6,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BEDROCK',
    'id': 7,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WATER',
    'id': 8,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STATIONARY_WATER',
    'id': 9,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LAVA',
    'id': 10,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STATIONARY_LAVA',
    'id': 11,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SAND',
    'id': 12,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GRAVEL',
    'id': 13,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLD_ORE',
    'id': 14,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_ORE',
    'id': 15,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COAL_ORE',
    'id': 16,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LOG',
    'id': 17,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LEAVES',
    'id': 18,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SPONGE',
    'id': 19,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GLASS',
    'id': 20,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LAPIS_ORE',
    'id': 21,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LAPIS_BLOCK',
    'id': 22,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DISPENSER',
    'id': 23,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SANDSTONE',
    'id': 24,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NOTE_BLOCK',
    'id': 25,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BED_BLOCK',
    'id': 26,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'POWERED_RAIL',
    'id': 27,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DETECTOR_RAIL',
    'id': 28,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PISTON_STICKY_BASE',
    'id': 29,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WEB',
    'id': 30,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LONG_GRASS',
    'id': 31,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DEAD_BUSH',
    'id': 32,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PISTON_BASE',
    'id': 33,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PISTON_EXTENSION',
    'id': 34,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOL',
    'id': 35,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PISTON_MOVING_PIECE',
    'id': 36,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'YELLOW_FLOWER',
    'id': 37,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RED_ROSE',
    'id': 38,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BROWN_MUSHROOM',
    'id': 39,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RED_MUSHROOM',
    'id': 40,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLD_BLOCK',
    'id': 41,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_BLOCK',
    'id': 42,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DOUBLE_STEP',
    'id': 43,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STEP',
    'id': 44,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BRICK',
    'id': 45,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'TNT',
    'id': 46,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BOOKSHELF',
    'id': 47,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MOSSY_COBBLESTONE',
    'id': 48,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'OBSIDIAN',
    'id': 49,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'TORCH',
    'id': 50,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FIRE',
    'id': 51,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MOB_SPAWNER',
    'id': 52,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_STAIRS',
    'id': 53,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CHEST',
    'id': 54,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_WIRE',
    'id': 55,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIAMOND_ORE',
    'id': 56,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIAMOND_BLOCK',
    'id': 57,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WORKBENCH',
    'id': 58,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CROPS',
    'id': 59,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SOIL',
    'id': 60,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FURNACE',
    'id': 61,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BURNING_FURNACE',
    'id': 62,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SIGN_POST',
    'id': 63,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOODEN_DOOR',
    'id': 64,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LADDER',
    'id': 65,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RAILS',
    'id': 66,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COBBLESTONE_STAIRS',
    'id': 67,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WALL_SIGN',
    'id': 68,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LEVER',
    'id': 69,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STONE_PLATE',
    'id': 70,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_DOOR_BLOCK',
    'id': 71,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_PLATE',
    'id': 72,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_ORE',
    'id': 73,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GLOWING_REDSTONE_ORE',
    'id': 74,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_TORCH_OFF',
    'id': 75,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_TORCH_ON',
    'id': 76,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STONE_BUTTON',
    'id': 77,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SNOW',
    'id': 78,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ICE',
    'id': 79,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SNOW_BLOCK',
    'id': 80,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CACTUS',
    'id': 81,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CLAY',
    'id': 82,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SUGAR_CANE_BLOCK',
    'id': 83,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'JUKEBOX',
    'id': 84,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FENCE',
    'id': 85,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PUMPKIN',
    'id': 86,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHERRACK',
    'id': 87,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SOUL_SAND',
    'id': 88,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GLOWSTONE',
    'id': 89,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PORTAL',
    'id': 90,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'JACK_O_LANTERN',
    'id': 91,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CAKE_BLOCK',
    'id': 92,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIODE_BLOCK_OFF',
    'id': 93,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIODE_BLOCK_ON',
    'id': 94,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LOCKED_CHEST',
    'id': 95,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'TRAP_DOOR',
    'id': 96,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MONSTER_EGGS',
    'id': 97,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SMOOTH_BRICK',
    'id': 98,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'HUGE_MUSHROOM_1',
    'id': 99,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'HUGE_MUSHROOM_2',
    'id': 100,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_FENCE',
    'id': 101,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'THIN_GLASS',
    'id': 102,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MELON_BLOCK',
    'id': 103,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PUMPKIN_STEM',
    'id': 104,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MELON_STEM',
    'id': 105,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'VINE',
    'id': 106,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FENCE_GATE',
    'id': 107,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BRICK_STAIRS',
    'id': 108,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SMOOTH_STAIRS',
    'id': 109,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MYCEL',
    'id': 110,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WATER_LILY',
    'id': 111,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHER_BRICK',
    'id': 112,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHER_FENCE',
    'id': 113,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHER_BRICK_STAIRS',
    'id': 114,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHER_WARTS',
    'id': 115,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENCHANTMENT_TABLE',
    'id': 116,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BREWING_STAND',
    'id': 117,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CAULDRON',
    'id': 118,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENDER_PORTAL',
    'id': 119,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENDER_PORTAL_FRAME',
    'id': 120,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENDER_STONE',
    'id': 121,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DRAGON_EGG',
    'id': 122,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_LAMP_OFF',
    'id': 123,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'REDSTONE_LAMP_ON',
    'id': 124,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_DOUBLE_STEP',
    'id': 125,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_STEP',
    'id': 126,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COCOA',
    'id': 127,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SANDSTONE_STAIRS',
    'id': 128,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'EMERALD_ORE',
    'id': 129,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENDER_CHEST',
    'id': 130,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'TRIPWIRE_HOOK',
    'id': 131,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'TRIPWIRE',
    'id': 132,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'EMERALD_BLOCK',
    'id': 133,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SPRUCE_WOOD_STAIRS',
    'id': 134,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BIRCH_WOOD_STAIRS',
    'id': 135,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'JUNGLE_WOOD_STAIRS',
    'id': 136,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COMMAND',
    'id': 137,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BEACON',
    'id': 138,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COBBLE_WALL',
    'id': 139,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FLOWER_POT',
    'id': 140,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CARROT',
    'id': 141,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'POTATO',
    'id': 142,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_BUTTON',
    'id': 143,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SKULL',
    'id': 144,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ANVIL',
    'id': 145,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_SPADE',
    'id': 256,
    'stack': 1,
    'durability': 250,
  },
  {
    'name': 'IRON_PICKAXE',
    'id': 257,
    'stack': 1,
    'durability': 250,
  },
  {
    'name': 'IRON_AXE',
    'id': 258,
    'stack': 1,
    'durability': 250,
  },
  {
    'name': 'FLINT_AND_STEEL',
    'id': 259,
    'stack': 1,
    'durability': 64,
  },
  {
    'name': 'APPLE',
    'id': 260,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BOW',
    'id': 261,
    'stack': 1,
    'durability': 384,
  },
  {
    'name': 'ARROW',
    'id': 262,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COAL',
    'id': 263,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'DIAMOND',
    'id': 264,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_INGOT',
    'id': 265,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLD_INGOT',
    'id': 266,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'IRON_SWORD',
    'id': 267,
    'stack': 1,
    'durability': 250,
  },
  {
    'name': 'WOOD_SWORD',
    'id': 268,
    'stack': 1,
    'durability': 59,
  },
  {
    'name': 'WOOD_SPADE',
    'id': 269,
    'stack': 1,
    'durability': 59,
  },
  {
    'name': 'WOOD_PICKAXE',
    'id': 270,
    'stack': 1,
    'durability': 59,
  },
  {
    'name': 'WOOD_AXE',
    'id': 271,
    'stack': 1,
    'durability': 59,
  },
  {
    'name': 'STONE_SWORD',
    'id': 272,
    'stack': 1,
    'durability': 131,
  },
  {
    'name': 'STONE_SPADE',
    'id': 273,
    'stack': 1,
    'durability': 131,
  },
  {
    'name': 'STONE_PICKAXE',
    'id': 274,
    'stack': 1,
    'durability': 131,
  },
  {
    'name': 'STONE_AXE',
    'id': 275,
    'stack': 1,
    'durability': 131,
  },
  {
    'name': 'DIAMOND_SWORD',
    'id': 276,
    'stack': 1,
    'durability': 1561,
  },
  {
    'name': 'DIAMOND_SPADE',
    'id': 277,
    'stack': 1,
    'durability': 1561,
  },
  {
    'name': 'DIAMOND_PICKAXE',
    'id': 278,
    'stack': 1,
    'durability': 1561,
  },
  {
    'name': 'DIAMOND_AXE',
    'id': 279,
    'stack': 1,
    'durability': 1561,
  },
  {
    'name': 'STICK',
    'id': 280,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BOWL',
    'id': 281,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MUSHROOM_SOUP',
    'id': 282,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'GOLD_SWORD',
    'id': 283,
    'stack': 1,
    'durability': 32,
  },
  {
    'name': 'GOLD_SPADE',
    'id': 284,
    'stack': 1,
    'durability': 32,
  },
  {
    'name': 'GOLD_PICKAXE',
    'id': 285,
    'stack': 1,
    'durability': 32,
  },
  {
    'name': 'GOLD_AXE',
    'id': 286,
    'stack': 1,
    'durability': 32,
  },
  {
    'name': 'STRING',
    'id': 287,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FEATHER',
    'id': 288,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SULPHUR',
    'id': 289,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WOOD_HOE',
    'id': 290,
    'stack': 1,
    'durability': 59,
  },
  {
    'name': 'STONE_HOE',
    'id': 291,
    'stack': 1,
    'durability': 131,
  },
  {
    'name': 'IRON_HOE',
    'id': 292,
    'stack': 1,
    'durability': 250,
  },
  {
    'name': 'DIAMOND_HOE',
    'id': 293,
    'stack': 1,
    'durability': 1561,
  },
  {
    'name': 'GOLD_HOE',
    'id': 294,
    'stack': 1,
    'durability': 32,
  },
  {
    'name': 'SEEDS',
    'id': 295,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'WHEAT',
    'id': 296,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BREAD',
    'id': 297,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'LEATHER_HELMET',
    'id': 298,
    'stack': 1,
    'durability': 55,
  },
  {
    'name': 'LEATHER_CHESTPLATE',
    'id': 299,
    'stack': 1,
    'durability': 80,
  },
  {
    'name': 'LEATHER_LEGGINGS',
    'id': 300,
    'stack': 1,
    'durability': 75,
  },
  {
    'name': 'LEATHER_BOOTS',
    'id': 301,
    'stack': 1,
    'durability': 65,
  },
  {
    'name': 'CHAINMAIL_HELMET',
    'id': 302,
    'stack': 1,
    'durability': 165,
  },
  {
    'name': 'CHAINMAIL_CHESTPLATE',
    'id': 303,
    'stack': 1,
    'durability': 240,
  },
  {
    'name': 'CHAINMAIL_LEGGINGS',
    'id': 304,
    'stack': 1,
    'durability': 225,
  },
  {
    'name': 'CHAINMAIL_BOOTS',
    'id': 305,
    'stack': 1,
    'durability': 195,
  },
  {
    'name': 'IRON_HELMET',
    'id': 306,
    'stack': 1,
    'durability': 165,
  },
  {
    'name': 'IRON_CHESTPLATE',
    'id': 307,
    'stack': 1,
    'durability': 240,
  },
  {
    'name': 'IRON_LEGGINGS',
    'id': 308,
    'stack': 1,
    'durability': 225,
  },
  {
    'name': 'IRON_BOOTS',
    'id': 309,
    'stack': 1,
    'durability': 195,
  },
  {
    'name': 'DIAMOND_HELMET',
    'id': 310,
    'stack': 1,
    'durability': 363,
  },
  {
    'name': 'DIAMOND_CHESTPLATE',
    'id': 311,
    'stack': 1,
    'durability': 528,
  },
  {
    'name': 'DIAMOND_LEGGINGS',
    'id': 312,
    'stack': 1,
    'durability': 495,
  },
  {
    'name': 'DIAMOND_BOOTS',
    'id': 313,
    'stack': 1,
    'durability': 429,
  },
  {
    'name': 'GOLD_HELMET',
    'id': 314,
    'stack': 1,
    'durability': 77,
  },
  {
    'name': 'GOLD_CHESTPLATE',
    'id': 315,
    'stack': 1,
    'durability': 112,
  },
  {
    'name': 'GOLD_LEGGINGS',
    'id': 316,
    'stack': 1,
    'durability': 105,
  },
  {
    'name': 'GOLD_BOOTS',
    'id': 317,
    'stack': 1,
    'durability': 91,
  },
  {
    'name': 'FLINT',
    'id': 318,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PORK',
    'id': 319,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GRILLED_PORK',
    'id': 320,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PAINTING',
    'id': 321,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLDEN_APPLE',
    'id': 322,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SIGN',
    'id': 323,
    'stack': 16,
    'durability': 0,
  },
  {
    'name': 'WOOD_DOOR',
    'id': 324,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'BUCKET',
    'id': 325,
    'stack': 16,
    'durability': 0,
  },
  {
    'name': 'WATER_BUCKET',
    'id': 326,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'LAVA_BUCKET',
    'id': 327,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'MINECART',
    'id': 328,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'SADDLE',
    'id': 329,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'IRON_DOOR',
    'id': 330,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'REDSTONE',
    'id': 331,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SNOW_BALL',
    'id': 332,
    'stack': 16,
    'durability': 0,
  },
  {
    'name': 'BOAT',
    'id': 333,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'LEATHER',
    'id': 334,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MILK_BUCKET',
    'id': 335,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'CLAY_BRICK',
    'id': 336,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CLAY_BALL',
    'id': 337,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SUGAR_CANE',
    'id': 338,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PAPER',
    'id': 339,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BOOK',
    'id': 340,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SLIME_BALL',
    'id': 341,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'STORAGE_MINECART',
    'id': 342,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'POWERED_MINECART',
    'id': 343,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'EGG',
    'id': 344,
    'stack': 16,
    'durability': 0,
  },
  {
    'name': 'COMPASS',
    'id': 345,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FISHING_ROD',
    'id': 346,
    'stack': 1,
    'durability': 64,
  },
  {
    'name': 'WATCH',
    'id': 347,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GLOWSTONE_DUST',
    'id': 348,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RAW_FISH',
    'id': 349,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COOKED_FISH',
    'id': 350,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'INK_SACK',
    'id': 351,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BONE',
    'id': 352,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SUGAR',
    'id': 353,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CAKE',
    'id': 354,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'BED',
    'id': 355,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'DIODE',
    'id': 356,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COOKIE',
    'id': 357,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MAP',
    'id': 358,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SHEARS',
    'id': 359,
    'stack': 1,
    'durability': 238,
  },
  {
    'name': 'MELON',
    'id': 360,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PUMPKIN_SEEDS',
    'id': 361,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MELON_SEEDS',
    'id': 362,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RAW_BEEF',
    'id': 363,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COOKED_BEEF',
    'id': 364,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'RAW_CHICKEN',
    'id': 365,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'COOKED_CHICKEN',
    'id': 366,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ROTTEN_FLESH',
    'id': 367,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ENDER_PEARL',
    'id': 368,
    'stack': 16,
    'durability': 0,
  },
  {
    'name': 'BLAZE_ROD',
    'id': 369,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GHAST_TEAR',
    'id': 370,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLD_NUGGET',
    'id': 371,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'NETHER_STALK',
    'id': 372,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'POTION',
    'id': 373,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'GLASS_BOTTLE',
    'id': 374,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SPIDER_EYE',
    'id': 375,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FERMENTED_SPIDER_EYE',
    'id': 376,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BLAZE_POWDER',
    'id': 377,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MAGMA_CREAM',
    'id': 378,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BREWING_STAND_ITEM',
    'id': 379,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CAULDRON_ITEM',
    'id': 380,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'EYE_OF_ENDER',
    'id': 381,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SPECKLED_MELON',
    'id': 382,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'MONSTER_EGG',
    'id': 383,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'EXP_BOTTLE',
    'id': 384,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FIREBALL',
    'id': 385,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BOOK_AND_QUILL',
    'id': 386,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'WRITTEN_BOOK',
    'id': 387,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'EMERALD',
    'id': 388,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'ITEM_FRAME',
    'id': 389,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'FLOWER_POT_ITEM',
    'id': 390,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CARROT_ITEM',
    'id': 391,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'POTATO_ITEM',
    'id': 392,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'BAKED_POTATO',
    'id': 393,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'POISONOUS_POTATO',
    'id': 394,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'EMPTY_MAP',
    'id': 395,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLDEN_CARROT',
    'id': 396,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'SKULL_ITEM',
    'id': 397,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'CARROT_STICK',
    'id': 398,
    'stack': 1,
    'durability': 25,
  },
  {
    'name': 'NETHER_STAR',
    'id': 399,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'PUMPKIN_PIE',
    'id': 400,
    'stack': 64,
    'durability': 0,
  },
  {
    'name': 'GOLD_RECORD',
    'id': 2256,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'GREEN_RECORD',
    'id': 2257,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_3',
    'id': 2258,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_4',
    'id': 2259,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_5',
    'id': 2260,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_6',
    'id': 2261,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_7',
    'id': 2262,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_8',
    'id': 2263,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_9',
    'id': 2264,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_10',
    'id': 2265,
    'stack': 1,
    'durability': 0,
  },
  {
    'name': 'RECORD_11',
    'id': 2266,
    'stack': 1,
    'durability': 0,
  },
]
